### ISSUE TITLE
Display historical data of test expectations as graph

### ISSUE THREAD

**Issue by whimboo** [puppeteer/ispuppeteerfirefoxready#1]
To improve the page to display current numbers and not those from the local copy of the expected data, we could do the following:

1. Grab the [JSON history data](https://hg.mozilla.org/mozilla-central/json-log/tip/remote/puppeteer-expected.json) of the file

2. For each `entry`:
2.1. Retrieve the push date via `entry[index][pushdate][0]` 
2.2.  Extract the revision via `entry[index][node]` and request the [raw content of the file](https://hg.mozilla.org/mozilla-central/raw-file/a1152a9c5dc53f54cb578b8a64289905a883100a/remote/puppeteer-expected.json)

3. The number of `PASS`, `FAIL`, `SKIP`, and `total` tests could be then displayed in a graph like: 

<img width="586" alt="Screenshot 2020-05-13 at 09 42 34" src="https://user-images.githubusercontent.com/129603/81785134-3335f680-94fe-11ea-9577-de62a5e878ae.png">

I assume that requesting the data via `fetch` will work cross-domain? If that is the case it shouldn't be that hard to get a nice status history displayed.

Any suggestions for such a library we could use for the graphs?

**Comment by whimboo** [comment]
CC @mathiasbynens, @mjzffr, @digitarald, @jgraham

**Comment by mathiasbynens** [comment]
Is there any chance you could enable CORS for those JSON endpoints? That way we could do all the data gathering on the client side during build time (see our current setup which uses Puppeteer to server-side render the resulting HTML), which would be nice.

For now we'll work around it.

**Comment by whimboo** [comment]
Or could the [newly added cron job](https://github.com/puppeteer/ispuppeteerfirefoxready/blob/master/.github/workflows/main.yml) in TravisCI do the fetch work?

**Comment by mathiasbynens** [comment]
@whimboo That's the workaround I had in mind.

**Comment by jgraham** [comment]
I think the hg people might be skeptical about adding CORS there; having every client fetch the data might be unacceptable additional load.

**Comment by mathiasbynens** [comment]
@jgraham Note that we'd _only_ be using this during local development. Our build process turns everything into static HTML. I suppose there's a risk that others will start depending on the JSON endpoints once they're CORS-friendly...

**Comment by mathiasbynens** [comment]
For the charts, our requirements are:

- it must produce SVG for zoomability/scalability
- the generated SVG DOM must be self-contained (i.e. `outerHTML` must be copy-and-pastable to a new HTML document and still render correctly)

There’s a few options that meet these requirements.

With Google Charts:

- [simple area chart](https://developers.google.com/chart/interactive/docs/gallery/areachart)

Or with d3.js:

- [stacked normalized horizontal bar chart](https://observablehq.com/@d3/stacked-normalized-horizontal-bar)
- [stacked area chart](https://observablehq.com/@d3/stacked-area-chart)

**Comment by whimboo** [comment]
> With Google Charts:
> 
>     * [simple area chart](https://developers.google.com/chart/interactive/docs/gallery/areachart)

Personally I would prefer a stacked chart. And note that Google charts has a `isStacked` property, so that d3.js wouldn't be necessary.

**Comment by mathiasbynens** [comment]
There's now a chart version: https://puppeteer.github.io/ispuppeteerfirefoxready/ Note that this only considers tests with a single expectation: https://github.com/puppeteer/ispuppeteerfirefoxready/blob/fac13b19d6ba67530f13a2e216f1431ea2ceeb26/preprocess-data.js#L15 Should we consider all expectations? (That might make the chart less useful, since it'd count the `PASS` in `[PASS, FAIL]`.)

**Comment by whimboo** [comment]
Yes, that looks great! Thanks a lot.

Regarding the results with multiple expectations I'm fine with that. Right now those are even 7 overall only, so not such a big change.

**Comment by whimboo** [comment]
I think we can close this issue now given that the historical data is visible. Thanks a lot @mathiasbynens for setting this up!
