### ISSUE TITLE
Dashboard does no longer update since Nov 2021

### ISSUE THREAD

**Issue by whimboo** [puppeteer/ispuppeteerfirefoxready#12]
As it looks like the dashboard does no longer update since around mid November 2021:
https://puppeteer.github.io/ispuppeteerfirefoxready/

@mathiasbynens is there some service not running? Or does it need a manual trigger? 

It would be great if you could have a look. Thanks a lot.

**Comment by mathiasbynens** [comment]
Ugh, this is annoying:

![](https://user-images.githubusercontent.com/81942/149886246-d028d53b-9575-489f-a0b2-89b58cbc64ea.png)

I _think_ we could set up the action to use a user token instead, so that any automated commits "count" as activity.

**Comment by mathiasbynens** [comment]
I’ve kicked off a manual build now: https://github.com/puppeteer/ispuppeteerfirefoxready/actions/workflows/main.yml

**Comment by whimboo** [comment]
Thanks! The chart has been updated now and shows up-to-date numbers.

**Comment by mathiasbynens** [comment]
I’ve also invited you to the repo (I was surprised you didn’t have access already, my bad!) and gave you the ability to trigger this workflow manually using the link posted above. Feel free to give that a try :)

**Comment by whimboo** [comment]
Great! I'll use it whenever we made changes to Firefox and the graph doesn't reflect it.
