### ISSUE TITLE
Count multiple expectation status as failure

### ISSUE THREAD

**Issue by whimboo** [puppeteer/ispuppeteerfirefoxready#5]
Right now the graph doesn't display those test results that have multiple statuses in the expected json file. This actually leaves a disconnect behind, which makes it hard to explain.

@mathiasbynens could we please count multiple status entries as failures instead?

Thanks!

**Comment by mathiasbynens** [comment]
Previous discussion (with a different outcome): https://github.com/puppeteer/ispuppeteerfirefoxready/issues/1#issuecomment-634051593

Definitely open to this change. I'm not sure I'll get to this soon, but please feel free to send a patch -- it's a matter of changing https://github.com/puppeteer/ispuppeteerfirefoxready/blob/main/preprocess-data.js.

**Comment by whimboo** [comment]
Fixed by #6.
