### ISSUE TITLE
Build & deploy job fails

### ISSUE THREAD

**Issue by whimboo** [puppeteer/ispuppeteerfirefoxready#7]
https://github.com/whimboo/ispuppeteerfirefoxready/actions/runs/148572467

> The ssh-private-key argument is empty. Maybe the secret has not been configured, or you are using a wrong secret name in your workflow file.

**Comment by mathiasbynens** [comment]
That's a run on your own fork, which doesn't have the secret set up. Feel free to push up a branch to this repository instead of your fork. The GitHub Action is only supposed to run for the `main` branch anyhow.

**Comment by whimboo** [comment]
Oh, I see. In that case it's invalid. 

In case I have the permissions I'm happy to directly push a branch to this repository instead.

**Comment by mathiasbynens** [comment]
@whimboo You should have the permissions. You could even push straight to `main` if you wanted.
